language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
env:
  - DJANGO_VERSION=1.11.6
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script: python manage.py test
services:
  - redis-server
